# Generated by Django 5.1.6 on 2025-02-28 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('position', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('position', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('engine_hours', models.IntegerField(default=0)),
                ('operator_team', models.CharField(max_length=255)),
                ('current_condition', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentcategories')),
                ('management_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentmanagementunit')),
            ],
        ),
    ]
