# Generated by Django 5.1.7 on 2025-03-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0003_alter_equipment_management_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='current_condition',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='operator_team',
        ),
    ]
