# Generated by Django 5.1.7 on 2025-03-22 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0004_remove_equipment_current_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='engine_hours',
            field=models.IntegerField(default=0, verbose_name='Giờ hoạt động (H)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='management_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentmanagementunit', verbose_name='Đơn vị quản lý'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment_management.manufacturer', verbose_name='Hãng sản xuất'),
        ),
    ]
