# Generated by Django 5.1.6 on 2025-03-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_management', '0005_manufacturer_alter_equipment_engine_hours_and_more'),
        ('maintenance', '0002_remove_replacementresult_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearPartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên vật tư')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn')),
                ('min_threshold', models.PositiveIntegerField(default=0, verbose_name='Tồn kho tối thiểu')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='Đơn vị')),
                ('manufacturer_id', models.CharField(max_length=50, unique=True, verbose_name='Mã vật tư hãng')),
                ('alternative_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã thay thế')),
            ],
            options={
                'verbose_name': 'Wear Part Stock',
                'verbose_name_plural': 'Wear Part Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('shortage', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancerecord')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenancetask', verbose_name='Task liên quan')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wear_part_stock.wearpartstock')),
            ],
            options={
                'verbose_name': 'Stock Movement Log',
                'verbose_name_plural': 'Stock Movement Logs',
            },
        ),
    ]
