# Generated by Django 5.1.7 on 2025-03-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacementresult',
            name='completed',
        ),
        migrations.AddField(
            model_name='replacementresult',
            name='actual_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Nhập số lượng vật tư thực tế đã thay trong quá trình bảo trì', verbose_name='Số lượng thực tế đã thay'),
        ),
        migrations.AlterField(
            model_name='completedmaintenancerecord',
            name='results',
            field=models.JSONField(default=list, verbose_name='Task Results'),
        ),
        migrations.AlterField(
            model_name='completedmaintenancerecord',
            name='tasks',
            field=models.JSONField(default=list, verbose_name='Maintenance Tasks'),
        ),
    ]
