# Generated by Django 5.1.6 on 2025-03-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_management', '0005_manufacturer_alter_equipment_engine_hours_and_more'),
        ('maintenance', '0002_remove_replacementresult_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Maintenance Location')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment_management.equipmentcategories', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_intermediate_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_maintenances', to='equipment_management.equipment', verbose_name='Equipment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_intermediate_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Intermediate Maintenance',
                'verbose_name_plural': 'Intermediate Maintenances',
            },
        ),
    ]
