# Generated by Django 5.1.6 on 2025-03-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_intermediatemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatemaintenance',
            name='engine_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Engine Hours'),
        ),
    ]
