# Generated by Django 5.1.7 on 2025-03-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment_management', '0004_remove_equipment_current_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_team', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operation Team')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='equipment_management.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Status',
                'verbose_name_plural': 'Equipment Statuses',
            },
        ),
    ]
