# Generated by Django 5.1.6 on 2025-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentstatus',
            name='engine_hours',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipmentstatus',
            name='management_unit_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
