# Generated by Django 5.1.6 on 2025-04-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_status', '0002_equipmentstatus_engine_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentstatus',
            name='engine_hours',
        ),
        migrations.RemoveField(
            model_name='equipmentstatus',
            name='management_unit_name',
        ),
    ]
